apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-client
  namespace: {{ .Values.namespace.default }}
spec:
  type: {{ .Values.client.serviceType }}
  selector:
    app: {{ .Values.app.name }}-client
  ports:
      - port: {{ .Values.client.port }}
        targetPort: {{ .Values.client.port }}


  