apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-mongo
  namespace: {{ .Values.namespace.default }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-mongo
    spec:
      containers:
          - name: mongo
            image: mongo:6
            ports:
              - containerPort: {{ .Values.mongo.port }}
        {{- if .Values.mongo.persistence }}
            volumeMounts:
              - name: mongo-data
                mountPath: /data/db
        {{- end }}
      {{- if .Values.mongo.persistence }}
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-mongo-pvc
      {{- end }}


  