apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-server
  namespace: {{ .Values.namespace.default }}
spec:
  type: {{ .Values.server.serviceType }}
  selector:
    app: {{ .Values.app.name }}-server
  ports:
      - name: http
        port: {{ .Values.server.port }}
        targetPort: {{ .Values.server.port }}


  