apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: boti95/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URL
              value: "mongodb://mongo:27017/employeesdb"
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - port: 8080
      targetPort: 8080
      name: http
